### ISSUE TITLE
Is the project not maintained?

### ISSUE THREAD

**Issue by JikkuJose** [erector/erector#67]
Is the project developed/maintained? If so, where is the typical discussion channel. I am very interested in the idea. Never knew something like this existed already! Let me know how I can contact the developers? I would love to contribute,

**Comment by jkingdon** [comment]
Perhaps we should point people to fortitude instead? As far as I can tell that is the one which is getting attention, and is more up to date (e.g. works better with tilt).

**Comment by alexch** [comment]
Perhaps :-)

Fortitude is more actively maintained, but not documented as far as I know.
But Erector is still around and the Fortitude team subscribes to its
discussion group.

Erector's docs: http://erector.github.io/erector/

Erector's mailing list: https://groups.google.com/forum/#!forum/erector

Fortitude: https://github.com/ageweke/fortitude

 - Alex

**Comment by jkingdon** [comment]
Fair enough, I haven't had occasion to use either erector or fortitude in a while, so it is a bit hard for me to speak to which one, or both, is likely to be useful to people.

This pull request makes some more modest changes to the README which perhaps would help: https://github.com/erector/erector/pull/68

@JikkuJose does this resolve your concern (such that we should close this issue)?

**Comment by JikkuJose** [comment]
@jkingdon thanks! I had stumbled on Fortitude from your discussion group. Its such a brilliant project. But I think it hasn't been active since last February?

**Comment by ageweke** [comment]
Just jumping in here briefly in case someone else comes to read this:

Fortitude was on hiatus for this summer (April–September 2015) because I was busy hiking the Pacific Crest Trail. However, I'm done now, and will be driving Fortitude hard towards reaching 1.0.0 and beyond: full documentation, all bugs fixed, and so on. I want it to have a long, good life for many years to come, and am pretty dedicated to that. :) So the activity break was a pause for a while, but definitely not the end of things in the least!
